# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Study-08' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Study-08
  pod 'DCAnimationKit'

end
