# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExLogin
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Firebase/Analytics'
pod 'GoogleSignIn'
end
